In [53]:
import torch
x_train = torch.FloatTensor([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0],
 [1,0,0], [1,0,0] ])

In [54]:
w = torch.randn(4, 3, requires_grad = True) # w,b 초기화
b = torch.randn(1, 3, requires_grad = True)

optimizer = torch.optim.Adam([w, b], lr = 0.1) # Optimizer 생성

In [55]:
for epoch in range(3001) :
  hypothesis = torch.softmax(torch.mm(x_train, w) + b, dim = 1)
  cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim = 1))
  hypothesis = (torch.mm(x_train, w) + b).softmax(dim = 1)
  cost = -(y_train * torch.log(hypothesis)).sum(dim = 1).mean()
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 300 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 8.774444
epoch: 300, cost: 0.183839
epoch: 600, cost: 0.088209
epoch: 900, cost: 0.051452
epoch: 1200, cost: 0.033456
epoch: 1500, cost: 0.023295
epoch: 1800, cost: 0.016999
epoch: 2100, cost: 0.012830
epoch: 2400, cost: 0.009931
epoch: 2700, cost: 0.007837
epoch: 3000, cost: 0.006279


In [56]:
w.requires_grad_(False)
b.requires_grad_(False)

x_test = torch.FloatTensor([[1,11,10,9], [1,3,4,3], [1,1,0,1]])
# x의 값이 [1,11,10,9], [1,3,4,3], [1,1,0,1]일때
test_all = torch.softmax(torch.mm(x_test, w) + b, dim=1)
print(test_all)
print(torch.argmax(test_all, dim=1))

tensor([[1.0000e+00, 2.5464e-15, 8.8374e-33],
        [2.3151e-01, 6.8680e-01, 8.1687e-02],
        [5.9586e-28, 1.4646e-10, 1.0000e+00]])
tensor([0, 1, 2])


In [57]:
import torch.nn.functional as F # softmax 함수 간단하게
import torch.nn as nn

In [58]:
# [1,0,0],[0,1,0],[0,0,1] 대신 0,1,2사용

# y_train = torch.FloatTensor([ [0,0,1], [0,0,1], [0,0,1], [0,1,0], [0,1,0], [0,1,0],
#  [1,0,0], [1,0,0] ])

y_train = torch.LongTensor([2,2,2,1,1,1,0,0])

In [59]:
# 기존의 w,b를 nn.Linear로 대체
# nn.Linear =  xTw + b

# 기존 코드
# w = torch.randn(4, 3, requires_grad = True)
# b = torch.randn(1, 3, requires_grad = True)
# optimizer = torch.optim.Adam([w, b], lr = 0.1)

model = nn.Linear(4,3)
optimizer = torch.optim.Adam(model.parameters(), lr=1)

In [60]:
for epoch in range(3001) :
  # hypothesis = torch.softmax(torch.mm(x_train, w) + b, dim = 1)
  # cost = -torch.mean(torch.sum(y_train * torch.log(hypothesis), dim = 1))
  # hypothesis = (torch.mm(x_train, w) + b).softmax(dim = 1)
  # cost = -(y_train * torch.log(hypothesis)).sum(dim = 1).mean()
  hypothesis = model(x_train)
  cost = F.cross_entropy(hypothesis, y_train)
  # 가설, 비용 함수를 제공하는 함수로 대체,  F.cross_entropy 는 softmax와 cross entropy를 합친 것
  optimizer.zero_grad()
  cost.backward()
  optimizer.step()
  if epoch % 100 == 0:
    print("epoch: {}, cost: {:.6f}".format(epoch, cost.item()))

epoch: 0, cost: 4.363610
epoch: 100, cost: 0.081484
epoch: 200, cost: 0.042999
epoch: 300, cost: 0.027075
epoch: 400, cost: 0.018684
epoch: 500, cost: 0.013724
epoch: 600, cost: 0.010541
epoch: 700, cost: 0.008370
epoch: 800, cost: 0.006818
epoch: 900, cost: 0.005667
epoch: 1000, cost: 0.004787
epoch: 1100, cost: 0.004099
epoch: 1200, cost: 0.003549
epoch: 1300, cost: 0.003101
epoch: 1400, cost: 0.002733
epoch: 1500, cost: 0.002424
epoch: 1600, cost: 0.002164
epoch: 1700, cost: 0.001942
epoch: 1800, cost: 0.001751
epoch: 1900, cost: 0.001586
epoch: 2000, cost: 0.001441
epoch: 2100, cost: 0.001315
epoch: 2200, cost: 0.001203
epoch: 2300, cost: 0.001103
epoch: 2400, cost: 0.001014
epoch: 2500, cost: 0.000935
epoch: 2600, cost: 0.000864
epoch: 2700, cost: 0.000799
epoch: 2800, cost: 0.000741
epoch: 2900, cost: 0.000688
epoch: 3000, cost: 0.000640


In [61]:
# Softmax Regression in Sklearn
import numpy as np
from sklearn.linear_model import LogisticRegression
x_train = np.array([ [1,2,1,1], [2,1,3,2], [3,1,3,4], [4,1,5,5], [1,7,5,5],
 [1,2,5,6], [1,6,6,6], [1,7,7,7] ])
# y에 0, 1, 2 등 둘 이상의 class가 존재 => softmax regression
y_train = np.array([ 2, 2, 2, 1, 1, 1, 0, 0 ])
logistic = LogisticRegression() # 모델 생성
logistic.fit(x_train, y_train) # 학습
pred = logistic.predict([[1,11,10,9], [1,3,4,3], [1,1,0,1]]) # test case (값 예측)
print(pred) # 출력

[0 2 2]
